reports:
  exclude_contracts:
    - SafeMath  # exclude SafeMath when calculating test coverage
dependencies:
  - smartcontractkit/chainlink-brownie-contracts@0.2.2
  - OpenZeppelin/openzeppelin-contracts-upgradeable@4.3.2
  - OpenZeppelin/openzeppelin-contracts@4.3.2
compiler:
  solc:
    remappings:
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@0.2.2"
      - '@openzeppelin/contracts-upgradeable=OpenZeppelin/openzeppelin-contracts-upgradeable@4.3.2/contracts'
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.3.2'
# automatically fetch contract sources from Etherscan
autofetch_sources: True
# Uncomment to use the .env file
dotenv: .env
# set a custom mnemonic for the development network
networks:
  default: rinkeby
  rinkeby:
    verify: False  # Change to True if you have an Etherscan API key and want to verify
    vrf_coordinator: "0xb3dCcb4Cf7a26f6cf6B120Cf5A73875B7BBc655B"
    link_token: "0x01be23585060835e02b77ef475b0cc51aa1e0709"
    keyhash: "0x2ed0feb3e7fd2022120aa84fab1945545a9f2ffc9076fd6156fa96eaff4c1311"
    fee: 100000000000000000
    oracle: "0xc57b33452b4f7bb189bb5afae9cc4aba1f7a4fd8"
    jobId: "6b88e0402e5d415eb946e528b8e0c7ba"
    eth_usd_price_feed: "0x8A753747A1Fa494EC906cE90E9f37563A8AF630e"
  hardhat:
    verify: False
wallets:
  from_key : ${PRIVATE_KEY}