[package]
name = "PortfolioOptimizerDAO"
version = "0.1.0"

[dependencies]
orion = { git = "https://github.com/gizatechxyz/orion" }
alexandria_data_structures = { git = "https://github.com/keep-starknet-strange/alexandria.git", rev = "f37d73d" }

[scripts]
test = "scarb cairo-test -f test"