[package]
name = "PortfolioOptimizerDAO"
version = "0.1.0"

[dependencies]
orion = { git = "https://github.com/gizatechxyz/orion", rev="v0.1.1" }
alexandria_math = { git = "https://github.com/keep-starknet-strange/alexandria.git" }

[scripts]
test = "scarb cairo-test -f test"